apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: telegraf
    app: telegraf-test
  name: telegraf
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: telegraf
    port: 9273
    targetPort: telegraf
    nodePort: 30079
  selector:
    app.kubernetes.io/name: telegraf
    app: telegraf-test
